#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput

exec granian --interface asgi1 \
  config.asgi \
  --host 0.0.0.0 \
  --port 5000 \
  --workers 4 \
  --threads 2 \
  --backlog 1024 \
  --timeout 120 \
  --log-level info